In [117]:
"""
Dan Ehrlich
6/20/18

OSM Lab
Intro to Numpy Module
"""

'\nDan Ehrlich\n6/20/18\n\nOSM Lab\nIntro to Numpy Module\n'

In [2]:
import numpy as np

In [3]:
'''
Problem 1
'''
def prob1(A,B):
    '''
    Function takes two matrices and takes their dot product.

    Input:
    A - Matrix that is n by m
    B - matrix that is m by n
    
    Output:
    Matrix dot product of A * B
    '''
    return A.dot(B)


A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2,6,-5,3],[5,-8,9,7],[9, -3,-2,-3]])
prob1(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [120]:
'''
Problem 2
'''
def prob2(A):
    '''
    Function takes a matrix and returns -A^3 + 9A^2 -15A.

    Input:
    A - Matrix that is n by n
    
    Output:
    Matrix dot that is -A^3 + 9A^2 -15A
    '''
    return -np.linalg.matrix_power(A, 3) + 9*np.linalg.matrix_power(A, 2) - 15*A

A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
prob2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [121]:
"""
Problem 3
"""
def prob3(A,B):
    '''
    Function takes two matrices and returns ABA.

    Input:
    A - Matrix that is n by n
    B - matrix that is n by n
    
    Output:
    Matrix dot product of ABA with type changed to np.int64
    '''
    answer = A.dot(B).dot(A)
    answer = answer.astype(np.int64)
    return answer

A= np.triu(np.ones((7,7)))
B = np.tril(np.full_like(A, -6)) + np.full_like(A, 5)
print(prob3(A,B))
print(prob3(A,B).dtype)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]
int64


In [122]:
"""
Problem 4
"""
def prob4(A):
    '''
    Function takes array as input and returns a copy of array with negative entires set to 0.

    Input:
    A  - array of any shape
    
    Output:
    Copy of array with negative entires set to 0.
    '''
    
    B = A.copy()
    mask = B < 0
    B[mask] = 0
    return B

A = np.array([5,6,7,-1,-2,-3])
prob4(A)

array([5, 6, 7, 0, 0, 0])

In [123]:
"""
Problem 5
"""

def prob5(A,B,C):
    '''
    Function takes three matrices as inputs and returns stacked matrix

    Input:
    A - Matrix that is n by n
    B - Matrix that is n by n
    C - Matrix that is n by n
    
    Output:
    Stacked Matrix 
    '''
    I = np.eye(C.shape[0])
    AT = A.T
    zero1 = np.zeros((AT.shape[0],A.shape[1]))
    zero2 = np.zeros((A.shape[0],AT.shape[1]))
    zero3 = np.zeros((A.shape[0],I.shape[1]))
    zero4 = np.zeros((B.shape[0],AT.shape[1]))
    
    return np.vstack((np.hstack((zero1,AT,I)), np.hstack((A,zero2,zero3)), np.hstack((B, zero4, C))))


A = np.arange(6).reshape((3,2)).T
B = np.tril(np.full((3, 3), 3))
C = np.diag([-2, -2, -2])
prob5(A,B,C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [16]:
"""
Problem 6
"""

def prob6(A):
    """
    Function takes matrix as input and divides each row by the row sum and 
    returns a row stochastic matrix. 
    
    Input: 
    A - Matrix that is n by m
    
    Output: 
    Row stochastic matrix
    """
    
    B = A.copy().astype(np.float64)
    rowsum = B.sum(axis = 1)[None,:].T
    return B/rowsum

A = np.arange(6).reshape((3,2))
prob6(A)

array([[ 0.        ,  1.        ],
       [ 0.4       ,  0.6       ],
       [ 0.44444444,  0.55555556]])

In [30]:
"""
Problem 7
"""

def prob7(grid):
    """
    Find the greatest product of four adjacent numbers in the same direction in a grid
    
    Input:
    Grid  - numpy array
    
    Output: 
    Maximum value - numpy array
    """
    
    maxright = np.max(grid[:,:-3]*grid[:,1:-2]*grid[:,2:-1]*grid[:,3:])
    maxdown = np.max(grid[:-3,:]*grid[1:-2,:]*grid[2:-1,:]*grid[3:,:])
    maxdiagr = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    maxdiagl = np.max(grid[3:,:-3]*grid[2:-1,1:-2]*grid[1:-2,2:-1]*grid[:-3,3:])
    maxright = max(maxright, maxdown, maxdiagr, maxdiagl)
    return maxright

grid = np.load("/Users/Deehrlich/Desktop/BootCamp2017/Computation/Wk1_PyIntro/grid.npy")
prob7(grid)

70600674