In [130]:
import numpy as np
import pandas as pd
from scipy import linalg as la
from scipy.sparse import csgraph

In [40]:
""" Problem 1 """

def drazin(A,k,AD):

    if np.allclose(A@AD, AD@A) and \
    np.allclose(np.linalg.matrix_power(A,k+1)@AD, np.linalg.matrix_power(A,k)) and \
    np.allclose(AD@A@AD,AD):
        return True
    else:
        return False

A = np.array([[1,3,0,0],[0,1,3,0],[0,0,1,3],[0,0,0,0]])
AD = np.array([[1,-3,9,81],[0,1,-3,-18],[0,0,1,3],[0,0,0,0]])
Ak = 1

B = np.array([[1,1,3],[5,2,6],[-2,-1,-3]])
BD = np.zeros_like(B)
Bk = 3

print(drazin(A,Ak,AD))
print(drazin(B,Bk,BD))

True
True


In [41]:
""" Problem 2 """

def get_Drazin(A,tol):
    n,n = A.shape
    f = lambda x: abs(x) > tol
    g = lambda x: abs(x) <= tol
    Q1,S,k1 = la.schur(A, sort=f)
    Q2,T,k2 = la.schur(A, sort=g)
    U = np.concatenate((S[:,:k1],T[:,:n-k1]),axis = 1)
    UI = la.inv(U)
    V = UI@A@U
    Z = np.zeros((n,n))
    if k1 != 0:
        MI = la.inv(V[:k1,:k1])
        Z[:k1,:k1] = MI
    return U@Z@UI

AD = get_Drazin(A,1e-5)
print(AD)
print(drazin(A,1,AD))

BD = get_Drazin(B,1e-5)
print(BD)
print(drazin(B,3,BD))

[[  1.  -3.   9.  81.]
 [  0.   1.  -3. -18.]
 [  0.   0.   1.   3.]
 [  0.   0.   0.   0.]]
True
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
True


In [122]:
""" Problem 3 """

def eff_resistance(A):
    n,n = A.shape
    L = csgraph.laplacian(A)
    R = np.zeros((n,n))
    I = np.eye(n)
    for i in range(n):
        Lj = np.copy(L)
        Lj[i,:] = I[i,:] 
        Lj_drazin = get_Drazin(Lj, 1e-5)
        R[:,i] = np.diag(Lj_drazin)
        R[i,i] = 0
    return R


#Figure 16.2, Column 2 Test
A = np.array([[0,1],[1,0]])
print("\n",eff_resistance(A))

B = np.array([[0,3],[3,0]])
print("\n", eff_resistance(B))

C = np.array([[0,4],[4,0]])
print("\n",eff_resistance(C))


 [[ 0.  1.]
 [ 1.  0.]]

 [[ 0.          0.33333333]
 [ 0.33333333  0.        ]]

 [[ 0.    0.25]
 [ 0.25  0.  ]]


In [12]:
""" Problem 4 """

class LinkPredictor():
    
    def __init__(self, filename):
    
        data = pd.read_csv(filename, header=None)
            
            
    def predict_link(self, node=None):
        
        
        if node == None:
            minval = np.min(R)
            loc = np.where(R == minval)
            return 
        else:
            
        
    def add_link(self, node1, node2):
        
        if node1 not in self.names:
            raise ValueError(node1, " not in list of names")
        if node2 not in self,names:
            raise ValueError(node2, " not in list of names")   
            
        

SyntaxError: invalid syntax (<ipython-input-12-62e4696c041a>, line 7)

In [123]:
with open("/Users/Deehrlich/Desktop/BootCamp2017/Computation/Wk3_Decomp/social_network.csv", 'r') as file:
            lines = file.readlines()

In [128]:
for line in lines:
line.split(',')

AttributeError: 'list' object has no attribute 'split'

In [139]:
data = pd.read_csv("/Users/Deehrlich/Desktop/BootCamp2017/Computation/Wk3_Decomp/social_network.csv",header=None)

In [140]:
data

0          1
0         Piers    Abigail
1         Piers     Oliver
2       Abigail     Oliver
3         Piers  Stephanie
4       Abigail  Stephanie
5        Oliver  Stephanie
6         Piers      Carol
7         Piers    Melanie
8         Piers    Stephen
9         Carol    Stephen
10      Melanie    Stephen
11        Piers      Sally
12      Abigail      Sally
13       Oliver      Sally
14    Stephanie      Sally
15        Piers   Penelope
16       Oliver   Penelope
17       Oliver       Alan
18        Piers     Trevor
19        Carol     Trevor
20      Melanie     Trevor
21        Piers       Jake
22        Piers       Mary
23    Stephanie       Mary
24        Piers       Anna
25      Abigail       Anna
26       Oliver       Anna
27    Stephanie       Anna
28      Melanie     Connor
29      Stephen     Connor
..          ...        ...
48         Jane     Tracey
49  Christopher     Tracey
50       Oliver      Sonia
51     Penelope      Sonia
52         Ruth      Sonia
53         Evan      Sonia
54          Max      Sonia
55      Theresa      Sonia
56    Alexander      Sonia
57        Colin      Sonia
58      Charles      Sonia
59    Madeleine      Sonia
60       Tracey      Sonia
61     Penelope      Emily
62         Alan      Emily
63         Anna      Emily
64         Ruth      Emily
65         Evan      Emily
66          Max      Emily
67         Eric      Emily
68      Theresa      Emily
69    Alexander      Emily
70        Colin      Emily
71      Brandon      Emily
72       Thomas      Emily
73  Christopher      Emily
74      Charles      Emily
75    Madeleine      Emily
76       Tracey      Emily
77        Sonia      Emily

[78 rows x 2 columns]