In [25]:
import numpy as np
from scipy import linalg as la
from scipy.sparse import csgraph

In [18]:
""" Problem 1 """

def drazin(A,k,AD):

    if np.allclose(A@AD, AD@A) and \
    np.allclose(np.linalg.matrix_power(A,k+1)@AD, np.linalg.matrix_power(A,k)) and \
    np.allclose(AD@A@AD,AD):
        return True
    else:
        return False

A = np.array([[1,3,0,0],[0,1,3,0],[0,0,1,3],[0,0,0,0]])
AD = np.array([[1,-3,9,81],[0,1,-3,-18],[0,0,1,3],[0,0,0,0]])
Ak = 1

B = np.array([[1,1,3],[5,2,6],[-2,-1,-3]])
BD = np.zeros_like(B)
Bk = 3

print(drazin(A,Ak,AD))
print(drazin(B,Bk,BD))

True
True


In [24]:
""" Problem 2 """

def get_Drazin(A,tol):
    n,n = A.shape
    f = lambda x: abs(x) > tol
    g = lambda x: abs(x) <= tol
    Q1,S,k1 = la.schur(A, sort=f)
    Q2,T,k2 = la.schur(A, sort=g)
    U = np.concatenate((S[:,:k1],T[:,:n-k1]),axis = 1)
    UI = la.inv(U)
    V = UI@A@U
    Z = np.zeros((n,n))
    if k1 != 0:
        MI = la.inv(V[:k1,:k1])
        Z[:k1,:k1] = MI
    return U@Z@UI

AD = get_Drazin(A,1e-5)
print(AD)
print(drazin(A,1,AD))

BD = get_Drazin(B,1e-5)
print(BD)
print(drazin(B,3,BD))

[[  1.  -3.   9.  81.]
 [  0.   1.  -3. -18.]
 [  0.   0.   1.   3.]
 [  0.   0.   0.   0.]]
True
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
True


In [ ]:
""" Problem 3 """

def eff_resistance(A):
    n,n = A.shape
    L = csgraph.laplacian(A)
    R = np.empty_like(A)
    I = np.eye(a)
    for j in range(n):
        Lj = L.copy()
        Lj[j,:] = I[j,:]
        LjD = get_Drazin(Lj, 1e-5)
        R[i,:] = np.diag(LjD)
        R[i,i] = 0
    return R


In [ ]:
""" Problem 4 """

class LinkPredictor:
    
    def __init__(self, filename):
    